### ISSUE TITLE
JDBC Importer Fixes

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#987] opened 2021-03-10 01:26 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The following issues we're identified by @cygnus-x-1 when testing the JDBC importer:
- You currently cannot add a connection without entering a username / password, even if it is not required.
- I'm unclear why there is an option for a username and password as that information was requested as part of the connection setup. Perhaps it was only needed for testing the connection there? If that's the case, then the UI should indicate that.
- The instructions in the 'Configuration' pane don't actually mention that you need to perform an SQL query to retrieve sample data before dragging and dropping attributes.
- I am unable to perform metadata queries of a database (.table, .schema , etc) as they fail validation.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** [What you expect to happen]

**Actual behaviour:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Auriga2** [comment] 2021-05-03 01:45
@cygnus-x-1 
> - You currently cannot add a connection without entering a username / password, even if it is not required.

What do you mean by ` it is not required.` here? Are there databases which don't require authentication to connect to? 
Currently a connection is added only after verified by `test`ing, which requires username and password. 

>- I'm unclear why there is an option for a username and password as that information was requested as part of the connection setup. Perhaps it was only needed for testing the connection there? If that's the case, then the UI should indicate that.

Username and password are used for testing a connection.  Hence we need them when adding a connection. They can be stored with the connection and used when querying in the plugin if it's safe enough to store them as strings in the SQLite database.  Or should we try to encrypt and decrypt the password?

**Comment by Auriga2** [comment] 2021-05-03 02:35
When adding a Driver, selecting the Jar file as the `Driver` populates the `Name` drop down. So we can we can place the `Name` after `Driver`. Also we can auto populate the name selection here, making it a locked field, because there's nothing in that drop down until then, and the drop down only populates a single name? Is it possible for a driver to populate multiple names here?

**Comment by GammaVel** [comment] 2021-05-18 05:55
Note for development - Need to support SQLite DBs

**Comment by Auriga2** [comment] 2021-05-20 02:42
Also found another bug where the JDBC importer didn't populate the 1st row from the query results, because the ConfigurationPane.createTableRows ignores it. (Because, in the delimited File Importer, the 1st row is considered as the column headers.) I think the above function should be fixed while `DilimitedImportController.updateSampleData` passing only the true data in `currentData` :
`configurationPane.setSampleData(currentColumns, currentData);`

**Comment by Auriga2** [comment] 2021-05-20 05:47
The issue with the SQLite DB mentioned in https://github.com/constellation-app/constellation/issues/141 could be reproduced and it was thrown when the  `ResultSetMetaData` (`PreparedStatement.getMetaData()`) was called after all of the rows of the `ResultSet` have been consumed, i.e., `rs.next()` has been called until it returns false. 

Easily fixed by moving that part of the code down, which wouldn't make any difference on other databases.

**Comment by Auriga2** [comment] 2021-05-21 03:51
Regarding the metadata queries, any query that works in a Query editor works here. 
E.g.: In SQLite, below queries work on the editor (I used `SQLiteStudio`) and Constellation editor.: 
```
SELECT *  FROM sqlite_master
PRAGMA TABLE_INFO(<Table_Name>);
```
Below fails in both editors, although work in the sqlite command line shell program:
But apparently they fail in editors due to syntax error, not related to validation.
```
.sch
.schema
```
The error message in SQLiteStudio:
![image](https://user-images.githubusercontent.com/64826928/119076372-97549a00-ba31-11eb-84f0-b8dbf824c4f4.png)
In Consty:
![image](https://user-images.githubusercontent.com/64826928/119078243-fa93fb80-ba34-11eb-93fd-8a2066b03e88.png)

I guess we don't need to support this syntax, similar to other editors. Also we can still query metadata through other queries via `sqlite_master`/ `sqlite_schema`. 
E.g.  Instead of `.tables`,
```
SELECT name FROM sqlite_schema
WHERE type='table'
ORDER BY name;
```

**Comment by Auriga2** [comment] 2021-05-24 07:05
With all the error pop ups, the exception was also thrown by the  LOGGER.log(). Fixed that also. 
The `Add Drive` window now lists the `Name` under the `Driver ` and `Name` auto populates the first item when the `Driver` is selected. I left the drop down, in case there could be multiple items for certain drivers perhaps.

**Closed** 2021-06-01 03:54 UTC
Labels: bug, user relevant
