### ISSUE TITLE
ConcurrentModificationException in the Analytic View

### ISSUE THREAD

**Issue by Nova-2119** [constellation-app/constellation#690] opened 2020-07-15 01:13 UTC
### Description
Whilst interacting with the Analytic View, looking at the categories and Questions I was able to get a java.util.ConcurrentModificationException.

### Steps to Reproduce
Non-Provided

**Expected behaviour:** [What you expect to happen]
There should be no error.

**Actual behaviour:** [What actually happens]
ConcurrentModificationError

**Reproduces how often:** [What percentage of the time does it reproduce?]
Unknown

**Comment by arcturus2** [comment] 2020-07-15 18:20
This is a duplicate of #196 which has been fixed.

**Closed by arcturus2** 2020-07-15 18:20 UTC
Labels: bug, duplicate
