### ISSUE TITLE
Scripting view is blank 

### ISSUE THREAD

**Issue by formalhaut69** [constellation-app/constellation#674] opened 2020-07-13 23:43 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The scripting view appears completely blank and not functional

### Steps to Reproduce

1. In a fresh constellation, open a new graph 
2. Run the sphere graph builder (Might not be a requirement)
3. Open the scripting view

**Expected behaviour:** The scripting view opens with no issue

**Actual behaviour:** The scripting view appears blank

**Reproduces how often:** 80%

### Additional Information

![image](https://user-images.githubusercontent.com/58677762/87364172-14151d00-c5b2-11ea-811f-85edef73a1a5.png)

**Comment by arcturus2** [comment] 2020-07-13 23:52
Normally when you click somewhere on the graph the scripting view appears. Can you see if that does the "trick". If so this would be the same behaviour as v1.3.1.

**Comment by formalhaut69** [comment] 2020-07-13 23:54
> Normally when you click somewhere on the graph the scripting view appears. Can you see if that does the "trick". If so this would be the same behaviour as v1.3.1.

Yep that seemed to work. Should I close the issue then?

**Comment by arcturus2** [comment] 2020-07-14 00:46
We can keep this as an open issue because it is a problem but can you remove the v2 tag?

**Comment by sol695510** [comment] 2021-03-05 07:47
Can anyone confirm whether this is still an issue? I can't seem to replicate the bug. @arcturus2 @antares1470 @aldebaran30701

**Comment by aldebaran30701** [comment] 2021-03-08 21:38
@sol695510 I have never been able to replicate this, it was something that seemed to be only replicable by @formalhaut69

**Comment by antares1470** [comment] 2021-03-08 22:03
> Can anyone confirm whether this is still an issue? I can't seem to replicate the bug. @arcturus2 @antares1470 @aldebaran30701

I followed the given reproducer and was able to recreate the bug

**Comment by OrionsGuardian** [comment] 2022-12-01 03:57
Not able to replicate this issue. Did a clean rebuild, ran a fresh first launch of constellation, followed the steps, and had no issue with the Scripting View.

**Comment by GammaVel** [comment] 2023-01-10 01:37
Agree with @OrionsGuardian, I can't replicate this issue. The scripting view is opening without any issues. Might have been something to do with the earlier version of Constellation or it might have been a unique set of steps that are needed to trigger the problem. 

Closing issue for now. @formalhaut69 if you can replicate this let us know and the issue can be reopened.

**Closed by GammaVel** 2023-01-10 01:37 UTC
Labels: bug
