### ISSUE TITLE
Switching between two graphs may result in an array out of bounds exception

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#561] opened 2020-06-04 00:03 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
Pressing tab and ctrl at the same time, multiple times will quick switch between two graphs. This sometimes caused the render exception to occur. 

### Steps to Reproduce
1. New graph
2. Sphere graph - 100 elements
3. New graph 
4. Sphere graph 1000 elements
5. Open a view (have recreated with New Table View and Quality Control View)
6. Switch between both graphs quickly

**Expected behaviour:** no error

**Actual behaviour:** errors
```
java.lang.ArrayIndexOutOfBoundsException: Index 4100 out of bounds for length 4096
	at au.gov.asd.tac.constellation.visual.opengl.utilities.glyphs.GlyphRectangleBuffer.addRectImage(GlyphRectangleBuffer.java:224)
	at au.gov.asd.tac.constellation.visual.opengl.utilities.glyphs.GlyphManagerBI.lambda$renderTextAsLigatures$5(GlyphManagerBI.java:421)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at au.gov.asd.tac.constellation.visual.opengl.utilities.glyphs.GlyphManagerBI.renderTextAsLigatures(GlyphManagerBI.java:415)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.batcher.NodeLabelBatcher.bufferTopLabel(NodeLabelBatcher.java:243)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.batcher.NodeLabelBatcher.fillTopLabels(NodeLabelBatcher.java:204)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.batcher.NodeLabelBatcher.createBatch(NodeLabelBatcher.java:157)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GraphRenderable.lambda$getChangeProcessor$3(GraphRenderable.java:162)
	at au.gov.asd.tac.constellation.utilities.visual.VisualProcessor.lambda$processChangeSet$1(VisualProcessor.java:296)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at au.gov.asd.tac.constellation.utilities.visual.VisualProcessor.lambda$processChangeSet$2(VisualProcessor.java:295)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at au.gov.asd.tac.constellation.utilities.visual.VisualProcessor.processChangeSet(VisualProcessor.java:293)
	at au.gov.asd.tac.constellation.utilities.visual.VisualProcessor.lambda$update$0(VisualProcessor.java:206)
[catch] at java.base/java.lang.Thread.run(Thread.java:834)
```

**Reproduces how often:** 
I've had it 4 times, but also tested around 10 times where it did not occur.

### Additional Information
N/A

**Comment by aldebaran30701** [comment] 2020-06-04 00:10
I just followed the reproducer, and opened the Data Access View and had the exception without having to switch graphs.

**Comment by Nova-2119** [comment] 2020-06-09 23:01
I experienced the same as above.
After closing and restarting constellation, then repeating the same process, I did not get an error.
After performing a clean build and then repeating the process I did not get an error.
If I delete the build folder, then do a c lean build, then repeat the process I get an error.
This above behavior is consistent and repeatable for me.

**Comment by Nova-2119** [comment] 2020-06-09 23:37
Error did not occur when I opened the larger graph first and then opened the table in the smaller graph (after build deletion and clean build)

**Comment by Nova-2119** [comment] 2020-06-10 04:22
Error occurs consistently when there are multiple graphs and you open the table view on the largest graph. Does not occur if you open the table view on one of the smaller graphs or if the graphs are of equal size.
Note that the table view still appears.

**Comment by Nova-2119** [comment] 2020-06-10 05:29
It was happening consistently earlier today....now i'm doing the same thing and not getting an error. Not as reproducible as I thought apparently.

**Comment by Nova-2119** [comment] 2020-06-10 05:39
I do have a suspicion about what may be causing it though. The error leads to https://github.com/constellation-app/constellation/blob/master/CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/utilities/glyphs/GlyphRectangleBuffer.java line 224 and is an index out of bounds error.

The if statement at line 216 increases the size of rectTextureCoordinates but only if ptr is the same size of it. Given ptr is defined as rectIndex * FLOATS_PER_RECT unless one of these is always 1 ptr will skip a bunch of numbers. My theory is that the error is occuring when ptr > rectTextureCoordinates.length and line 216  should read:             
if (ptr >= rectTextureCoordinates.length) {
rather than the current
if (ptr == rectTextureCoordinates.length) {

**Comment by Nova-2119** [comment] 2020-06-11 00:00
In the error I saved we have the line: "Index 2052 out of bounds for length 2048" meaning that rectTextureCoordinates has size 2048 (double its initial size, so we have hit the if statement in question once before) but ptr is size 2052 and was never of size 2048 (else the if statement would have been triggered). As far as I can tell things are added to memory 1 at a time, and hence ptrs should grow by 0 or 4 each time addRectImage is called. To me this implies that perhaps two instances or addRectImage are running simultaneously and this is sometimes causing two values to be added too memory.

I have now seen this jumping behavior in debug mode. When I opened the data access view ptr was jumping by two each iteration. Now I need to find out why.

**Comment by Nova-2119** [comment] 2020-06-11 23:11
I have confirmed that the problem is caused by there being multiple threads working on the same static variable. When two threads are performing addRectImage simultaneously sometimes the second thread (with the larger index) tries to add values to rectTextureCoordinates before the previous thread has had a chance to increase its size.

Now I need to confirm how much of this is desired behaviour and how much is wrong...should there be?
A) No Visual Processor threads
B) Only 1 Visual Processor Thread
C) Multiple Visual Processor Threads and if so:
    1) Should the static variable being accessed/modified be static?
    2) If so then make addRectImage threadsafe.

**Comment by Nova-2119** [comment] 2020-06-15 00:42
The visual processors are being triggered by VisualManager.refreshVisualProcessor which is being triggered by GLRenderer.dispose which is triggered by external libraries. The behavior of each seems to match the description, which makes me believe that this is desired behavior.

I also believe that the static glyphManager being accessed is meant to be static due to essentially acting as a repository of images for all graphs to access.

All of this suggests that the best way to fix the bug is to make addRectImage threadsafe.

However; the problem only occurs if multiple VisualProcessors try to retrieve an image that does not exist in the glyphManager. Before implementing a fix I want to find out what is causing this...it seems like odd behavior given the graph is only being rescaled (due to opening the table view changing the size of graph window) which makes me wonder why a new glyph is appearing?

As far as I can tell the only time that addRectImage is not threadsafe is when a new glyph is encountered, hence the answer to the above could impact the solution.

**Comment by Nova-2119** [comment] 2020-06-15 23:13
The GLRenderer.dispose method is being called multiple times from external code, for the purposes of this bug fix we will therefore assume it is desired behavior.

I have been unable to pinpoint why a new glyph is being created, however I think its reasonable to assume that if it shouldn't be then the problem would manifest in different ways in addition to this bug. So I wont get any further down the path.

I will make the part of addRectImage where the error is occurring threadsafe, this should fix the bug.

**Closed** 2020-06-21 18:36 UTC
Labels: bug, user relevant
