### ISSUE TITLE
Parameter errors with the analytic view

### ISSUE THREAD

**Issue by Nova-2119** [constellation-app/constellation#691] opened 2020-07-15 01:21 UTC
### Description
I was able to brake the analytic view and got the following error:
java.lang.IllegalArgumentException: Parameter 'ClosenessCentralityPlugin.harmonic' does not exist.

### Steps to Reproduce
Non-Provided

**Expected behaviour:** [What you expect to happen]
There should be no error.

**Actual behaviour:** [What actually happens]
Error as above.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Unknown

**Comment by arcturus2** [comment] 2020-07-15 18:21
This is a duplicate of #196 which has been fixed.

**Closed by arcturus2** 2020-07-15 18:21 UTC
Labels: bug, duplicate
