### ISSUE TITLE
Current graph out of sync with helpers etc

### ISSUE THREAD

**Issue by canis-majoris-42** [constellation-app/constellation#328] opened 2020-03-23 02:11 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Constellation sessions have gotten out of sync. The histogram and stats in bottom right of the tool are not for the graph in focus, but are stuck on one of the other graphs tabs currently open. Changing between graph tabs is not updating this.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** Views/bottom right stats always display for the current graph

**Actual behaviour:** Views/bottom right stats display information for the other tabbed graph

**Reproduces how often:** Sometimes

### Additional Information

N/A

**Comment by Auriga2** [comment] 2020-06-03 07:06
I cannot recreate this, even with large graphs loaded and loading. 
Tried graphs with 100000 nodes loaded, 1000000 loaded, 1000000 loading and 100000 loading nodes. The histogram and stats in bottom right change per graph.

**Comment by arcturus2** [comment] 2020-06-09 02:48
Thanks for testing this out @Auriga2. Could you try opening up all of the views and also "Find" (Ctrl + F) and try having say 4 graphs of say 50K nodes and try playing with the views and alternate between the graphs.

I think one of the problems similar to the DAV writing it's state is the Find View which can quickly take up a lot of write state locks and cause everything to lag.

**Comment by aldebaran30701** [comment] 2020-08-10 02:00
I tried to replicate this, following your latest comment @arcturus2.
I opened 4 graphs, with 45000, 46000, 48000, 50000 vertices each - using the sphere graph builder.
I switched between graphs and could not get them to come out of sync.
I opened find view and the application hung. No exceptions, just appeared to get stuck trying to update the find view state.

I've also tried other times to replicate this bug with no success

**Comment by arcturus2** [comment] 2020-08-10 02:49
Thanks for testing this again @aldebaran30701. I'd agree that based on testing by @Auriga2 and you that we can't reproduce the helpers getting out of sync. I'd be happy to close this as a can't reproduce.

However, the reproducer to get the app to lockup would be a good ticket if you can create that for me? You've got the reproducer steps already and we can tag it with performance and bug.

I know that we are creating and closing tickets so the total amount doesn't really change but creating a new ticket helps give closure to the current issue rather than renaming the title. It also helps with tracking issues.

**Comment by Nova-2119** [comment] 2020-09-01 22:29
@arcturus2 can we close this?

**Comment by antares1470** [comment] 2020-10-05 22:04
Are we happy to close this ticket? @arcturus2 were you wanting a ticket created for issue mentioned above before closing this?

**Comment by antares1470** [comment] 2020-10-07 00:31
Having created #852 to address issue mentioned above. Closing this ticket

**Closed by antares1470** 2020-10-07 00:31 UTC
Labels: bug, user relevant
