### ISSUE TITLE
Timeline summary window box can shrink unexpectedly

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#30] opened 2019-07-26 02:53 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

Dragging the Timeline's summary window box toward the right edge of the summary window will cause it to jump around and in the process slowly shrink.

### Steps to Reproduce

1. Create a sphere graph
2. Open the timeline view, making sure the summary window is visible
3. Drag the box in the summary window to the right edge
4. Keep trying to drag the box across and notice the timeline jump around and the box slowly shrink

**Expected behaviour:** Summary window box is not affected by forcing box beyond current summary window bounds
**Actual behaviour:** Summary window box shrinks when trying to go past summary window bounds

**Reproduces how often:** 100%

### Additional Information

The main effect of this bug is that it acts as an unexpected zoom in

**Comment by serpens24** [comment] 2020-01-09 02:36
@arcturus2 - I'm trying to replicate this issue, but may not be going about it the right way and the steps to reproduce arent filled in.
I've created a graph with some time based connecitons, then opened the timeline view and attempted to drag and resize what appears to be the summary view - see circled edge on attached file. I don't seem to be seeing the box shrink or resize.

![resize](https://user-images.githubusercontent.com/58677108/72032921-b4774580-32e0-11ea-9cc9-788834db57ea.png)

**Comment by antares1470** [comment] 2020-05-08 01:13
I've managed to recreate the bug and have updated the issue details with my findings

**Comment by antares1470** [comment] 2020-05-08 02:19
Panning across the timeline:
![timelineissue](https://user-images.githubusercontent.com/62311243/81363151-fc3e9a00-9125-11ea-9046-321ed1354dcd.gif)

Trying to drag box beyond summary window bounds:
![timelineissue2](https://user-images.githubusercontent.com/62311243/81363155-fea0f400-9125-11ea-8f35-d4fe9f57d1c0.gif)

**Comment by arcturus2** [comment] 2020-05-08 03:05
@serpens24 this is what I was wanting to gif for you. Thank you @antares1470 for doing it!

**Comment by antares1470** [comment] 2020-05-11 05:23
I've determined that the 2 problems identified in this ticket will need different solutions to be solved. I've separated them out and created a new issue #498 with the other problem

**Comment by antares1470** [comment] 2020-05-14 01:15
`performDrag()` in `OverviewPanel` is where it is determined whether or not dragging the summary box should be done. Whether it is done or not is determined by the following if condition in the function:
```
// Only perform drag if it is within the bounds of the histogram:
if (0.0 <= newX && (newX + rect.getWidth()) < histogram.getWidth()) {...
```
I don't think there is an issue with the if condition as this is used elsewhere and makes sense. What I have discovered during debugging though is that `histogram.getWidth()` may be changing value unexpectedly. This function will run multiple times depending on the size of the drag but every time the if condition evaluates to true this results in the histogram width changing somehow and I'm unsure as to why or how. Someone with more knowledge in this may be able to explain more as to what is actually being measured for the histogram width but my understanding is that this shouldn't be changed by this.

**Comment by antares1470** [comment] 2020-05-14 02:06
I finally worked it out, going one step up the function chain from `performDrag()` you get the following function:
```
private void handleDragging(final MouseEvent t) {
     //Resize POV if necessary:
     if (isResizingLeft || isResizingRight) {
          resizePOV(t);
     } else { // If we aren't resizing we are dragging:
          // only drag on 'x' press:
          performDrag(t);
     }

     // Update the origin as we have had some movement:
     origin = t.getX();
}
```
The issue here ends up being the final line which assumes that there has been movement when actually movement only occurs if it meets the boolean conditions within the functions. Since `origin` was used to help determine how far we have moved, this incorrect assumption from the last line of the above function is what is causing the problem. 

Moving this line to within the if conditions of the functions it calls seems to fix the issue

**Closed** 2020-05-15 05:21 UTC
Labels: bug, user relevant
