### ISSUE TITLE
Nasty labels bug

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#629] opened 2020-07-06 21:09 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

I've recently seen a nasty labels bug which needs to be fixed before v2 can be released.

![Screenshot from 2020-07-07 07-01-25](https://user-images.githubusercontent.com/39325530/86643112-c3d11480-c01f-11ea-94ee-714394e7d282.png)

![Peek 2020-07-07 06-58](https://user-images.githubusercontent.com/39325530/86643145-caf82280-c01f-11ea-9dae-a89aa767c6aa.gif)

### Steps to Reproduce

1. Open a new graph
2. Experimental -> Build Graph -> Small World Graph Builder
3. Open a new graph
4. Experimental -> Build Graph -> Sphere Graph Builder
5. Views -> Analytic View (any view is fine)
6. Close the Analytic View
7. Switch to the first graph (analyticgraph1)

**Expected behaviour:** Labels should never distort

**Actual behaviour:** Labels have blanks in between and at other times have letters on top of one another

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by arcturus2** [comment] 2020-07-06 21:41
The following stack trace may be related to this. I got this exception when I tried to close the Analytic View:

```
java.lang.IndexOutOfBoundsException
	at java.base/java.nio.FloatBuffer.wrap(FloatBuffer.java:395)
	at au.gov.asd.tac.constellation.visual.opengl.utilities.glyphs.GlyphManagerOpenGLController.updateCoordinates(GlyphManagerOpenGLController.java:106)
	at au.gov.asd.tac.constellation.visual.opengl.utilities.glyphs.GlyphManagerOpenGLController.update(GlyphManagerOpenGLController.java:69)
	at au.gov.asd.tac.constellation.visual.opengl.utilities.SharedDrawable.updateGlyphTextureController(SharedDrawable.java:226)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.batcher.NodeLabelBatcher.drawBatch(NodeLabelBatcher.java:320)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GraphRenderable.display(GraphRenderable.java:518)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GLRenderer.lambda$display$3(GLRenderer.java:170)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GLRenderer.display(GLRenderer.java:169)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at com.jogamp.opengl.awt.GLCanvas$11.run(GLCanvas.java:1428)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
Caused: com.jogamp.opengl.GLException: Caught IndexOutOfBoundsException: null on thread AWT-EventQueue-0
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.awt.GLCanvas$12.run(GLCanvas.java:1442)
	at com.jogamp.opengl.Threading.invoke(Threading.java:223)
	at com.jogamp.opengl.awt.GLCanvas.display(GLCanvas.java:503)
	at com.jogamp.opengl.awt.GLCanvas.paint(GLCanvas.java:557)
	at java.desktop/sun.awt.RepaintArea.paintComponent(RepaintArea.java:264)
	at java.desktop/sun.awt.X11.XRepaintArea.paintComponent(XRepaintArea.java:66)
	at java.desktop/sun.awt.RepaintArea.paint(RepaintArea.java:240)
	at java.desktop/sun.awt.X11.XComponentPeer.handleEvent(XComponentPeer.java:555)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5068)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4839)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by arcturus2** [comment] 2020-07-06 22:10
I've run v1.3.1 and have been able to reproduce this. Is it my new graphics card (MSI Radeon RX 570 Armor OC 4GB)? :cry: 

```
OpenGL version: 4.6 (Core Profile) Mesa 20.1.2
Vendor: X.Org
Renderer: Radeon RX 570 Series (POLARIS10, DRM 3.37.0, 5.7.6-201.fc32.x86_64, LLVM 10.0.0)
Shading language version: 4.60

JOGL Attributes
Ant-Version: Apache Ant 1.9.4
Application-Library-Allowable-Codebase: *
Application-Name: Java Bindings for OpenGL
Codebase: *.jogamp.org
Created-By: 1.8.0_60-b27 (Oracle Corporation)
Extension-Name: com.jogamp.opengl
Implementation-Branch: origin/master
Implementation-Build: 2.3-b1469-20151010
Implementation-Commit: e794fc40ba723f2fca4ac892e873975fb393e007
Implementation-Title: Java Bindings for OpenGL Runtime Environment
Implementation-URL: http://jogamp.org/
Implementation-Vendor-Id: com.jogamp
Implementation-Vendor: JogAmp Community
Implementation-Version: 2.3.2
Manifest-Version: 1.0
Permissions: all-permissions
Specification-Title: Java Bindings for OpenGL API Specification
Specification-Vendor: JogAmp Community
Specification-Version: 2.3
Trusted-Library: true

GL Strings
Swap Interval  1
GL Profile     GLProfile[GL4/GL4.hw]
GL Version     4.6 (Core profile, arb, compat[ES2, ES3, ES31, ES32], FBO, hardware) - 4.6 (Core Profile) Mesa 20.1.2 [GL 4.6.0, vendor 20.1.2 ((Core Profile) Mesa 20.1.2)]
Quirks         []
Impl. class    jogamp.opengl.gl4.GL4bcImpl
GL_VENDOR      X.Org
GL_RENDERER    Radeon RX 570 Series (POLARIS10, DRM 3.37.0, 5.7.6-201.fc32.x86_64, LLVM 10.0.0)
GL_VERSION     4.6 (Core Profile) Mesa 20.1.2
GLSL           true, has-compiler-func: true, version: 4.60 / 4.60.0
GL FBO: basic true, full true
GL_EXTENSIONS  225
               GL_AMD_conservative_depth GL_AMD_depth_clamp_separate GL_AMD_draw_buffers_blend GL_AMD_framebuffer_multisample_advanced GL_AMD_gpu_shader_int64 GL_AMD_multi_draw_indirect GL_AMD_performance_monitor GL_AMD_pinned_memory GL_AMD_query_buffer_object GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_AMD_shader_trinary_minmax GL_AMD_texture_texture4 GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_ES2_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compressed_texture_pixel_storage GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_indirect GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_stencil_export GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shader_viewport_layer_array GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_sparse_buffer GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map_array GL_ARB_texture_filter_anisotropic GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ATI_blend_equation_separate GL_ATI_meminfo GL_ATI_texture_float GL_ATI_texture_mirror_once GL_EXT_EGL_image_storage GL_EXT_EGL_sync GL_EXT_abgr GL_EXT_blend_equation_separate GL_EXT_depth_bounds_test GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_semaphore GL_EXT_semaphore_fd GL_EXT_shader_image_load_formatted GL_EXT_shader_image_load_store GL_EXT_shader_integer_mix GL_EXT_shader_samples_identical GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_mirror_clamp GL_EXT_texture_sRGB GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_decode GL_EXT_texture_shadow_lod GL_EXT_texture_shared_exponent GL_EXT_texture_snorm GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_EXT_window_rectangles GL_IBM_multimode_draw_arrays GL_KHR_blend_equation_advanced GL_KHR_context_flush_control GL_KHR_debug GL_KHR_no_error GL_KHR_parallel_shader_compile GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_sliced_3d GL_MESA_framebuffer_flip_y GL_MESA_pack_invert GL_MESA_shader_integer_functions GL_MESA_texture_signed_rgba GL_NVX_gpu_memory_info GL_NV_alpha_to_coverage_dither_control GL_NV_conditional_render GL_NV_copy_image GL_NV_depth_clamp GL_NV_packed_depth_stencil GL_NV_texture_barrier GL_NV_vdpau_interop GL_OES_EGL_image GL_S3_s3tc
GLX_EXTENSIONS 34
               GLX_ARB_context_flush_control GLX_ARB_create_context GLX_ARB_create_context_no_error GLX_ARB_create_context_profile GLX_ARB_create_context_robustness GLX_ARB_fbconfig_float GLX_ARB_framebuffer_sRGB GLX_ARB_get_proc_address GLX_ARB_multisample GLX_EXT_buffer_age GLX_EXT_create_context_es2_profile GLX_EXT_create_context_es_profile GLX_EXT_fbconfig_packed_float GLX_EXT_framebuffer_sRGB GLX_EXT_import_context GLX_EXT_texture_from_pixmap GLX_EXT_visual_info GLX_EXT_visual_rating GLX_INTEL_swap_event GLX_MESA_copy_sub_buffer GLX_MESA_multithread_makecurrent GLX_MESA_query_renderer GLX_MESA_swap_control GLX_OML_swap_method GLX_OML_sync_control GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGIX_visual_select_group GLX_SGI_make_current_read GLX_SGI_swap_control GLX_SGI_video_sync GLX_EXT_libglvnd GLX_EXT_no_config_context
-----------------------------------------------------------------------------------------------------
```

**Comment by aldebaran30701** [comment] 2020-07-06 22:56
While I haven't tested this just yet, I recall having issues like this relating to when I was testing the font updates.
https://github.com/constellation-app/constellation/pull/213#issuecomment-579574208

**Comment by Nova-2119** [comment] 2020-07-06 23:29
I have seen the same issue whilst working on my current ticket.

**Comment by Nova-2119** [comment] 2020-07-07 22:32
Can confirm that glyphs are being written over other glyphs. See the attached Glyph Textures for an example.
![glyphs_0](https://user-images.githubusercontent.com/66700235/86851001-8d65c900-c0f5-11ea-90fe-acae6acc240c.png)

**Comment by Nova-2119** [comment] 2020-07-07 22:34
Also I found a but in the glyph exporter that would cause the file to be stored in the wrong place if there was a "." in the filepath but not a file extension. I will create a ticket for this and upload a fix.

**Comment by Nova-2119** [comment] 2020-07-07 22:51
So the glyph textures is ruined when you open the view. It is fine after creating the second file but once you open the view you get the glyph texture seen above.
Its interesting to note that the glyps created by the first and second graph originally are still there but a bunch of extra ruined glyphs are created which graph one then uses. Graph 2 remains unaffected.

**Comment by Nova-2119** [comment] 2020-07-07 23:00
Bug repeats itself if you run through the same steps again without closing constellation. You can see the graphs use the original glyphs again before creating another bunch of ruined glyphs.

If you open the analytic view on graph one instead of graph two the problem still only affects graph one.

**Comment by Nova-2119** [comment] 2020-07-07 23:15
If you open the two graphs in the opposite order the small world graph is still the one that is affected. I can confirm that the graph affected is not based on the order the graphs are opened / the order their original glyphs are added or the graph on which you open the view.

**Comment by Nova-2119** [comment] 2020-07-08 00:57
Its a threading issue, multiple threads overwriting the same drawing by the looks of it. I synchronized renderTextAsLigatures and that seems to have stopped the problem from occurring.
Will submit the fix.

**Comment by Nova-2119** [comment] 2020-07-08 01:08
So for more detail this is my current understanding/theory. I'm not 100% on this, but it explains what I have seen.

SharedDrawable has a glyphManager variable which is static.
When the view is opened the visual managers each trigger a visual processor to handle the changes cause by the change in size of the graph window.
These both trigger NodleLabelBatcher.BuferTopLabel which calls the renderTextAsLigatures method from the same (static) glyphManager.
They both try and do things using the drawing variable in the glyphManager and one ends up overwriting the other, meaning all of the rectangle locations are bogus and resulting in weird new glyphs.

**Evidence:** Unable to recreate bug after Synchronizing the renderTextAsLigatures method . In debug mode I have tried printing the drawing and the associated subimage. The drawing always looks correct but the subimages sometimes look wrong. Both threads using renderTextAsLigatures method could be shown to have the same drawing.....pretty sure they shouldn't as the text in the drawing only appears in one of the graphs.
My reservation is that the issue is maybe too repeatable...id expect it to be a bit more random if it is a threading issue.

**Comment by Nova-2119** [comment] 2020-07-08 01:25
Can confirm that once sychronized both threads are accessing a different drawing which makes me pretty confident the issue is what I described above

**Comment by Nova-2119** [comment] 2020-07-08 02:39
submitted PR: https://github.com/constellation-app/constellation/pull/639/checks

**Closed** 2020-07-08 05:40 UTC
Labels: bug
