### ISSUE TITLE
REST API fails to find attributes with many null values.

### ISSUE THREAD

**Issue by Nova-2119** [constellation-app/constellation#683] opened 2020-07-15 00:01 UTC
### Description
Using the Python interface to the Constellation REST API, if you ask a dataframe using constellation_client.Constellation().get_dataframe() then you will receive one containing only attributes which have a high proportion of non-null values (somewhere between half and none).

### Steps to Reproduce
Non-Given

**Expected behaviour:** [What you expect to happen]
All attributes should be returned regardless of the proportion of null values.

**Actual behaviour:** [What actually happens]
Attributes with a high proportion of null values are not returned.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Unknown

**Comment by aldebaran30701** [comment] 2020-08-06 06:28
>Attributes with a high proportion of null values are not returned.

Does this refer to a graph that may have 100 vertices, and only 5 of them have an attribute which is not null. while the remainder have null as the attribute value?

I've been looking through the constellation_client.py for a hint as to why this may be about - but nothing really looks odd.

I haven't been able to recreate it yet.

**Comment by aldebaran30701** [comment] 2020-08-06 23:28
**UPDATE:**
I was able to recreate this once. 
I made 25 manually drawn vertices, grid arranged, then drew maybe 15 random transactions between some. 
I then added a `Content` attribute to the last vertex with the value "this is a non-null value" 

After running the query through a Jupyter notebook, I did not see the content attribute. 
I then added it to another 11, meaning it was 11/25 vertices had the attribute.
Re-ran the query, and it appeared.

I tried to recreate it again but with 4 vertices so I could debug it easier, but the `Content` attribute appeared even after a fresh reboot. 
I then tried the original reproducer, and it appeared 100% of the time and I have no longer been able to reproduce it. 

Since then I've been digging through `RecordStore` code and checking the `RestService` as well as ` constellation_client.py` to find if there is any checks for null, or something alike. No luck just yet.

It's very odd that I can't seem to get it recreating again.

**Comment by Nova-2119** [comment] 2020-08-27 01:35
I will have a look and see if I can get this to consistently occur.

**Comment by Nova-2119** [comment] 2020-08-27 04:27
@aldebaran30701 I seem unable to replicate this, do you reckon we can close this?

**Comment by antares1470** [comment] 2020-09-07 22:39
> 
> 
> @aldebaran30701 I seem unable to replicate this, do you reckon we can close this?

@arcturus2 @aldebaran30701 Do we have a verdict on this?

**Comment by aldebaran30701** [comment] 2020-09-07 22:53
@antares1470 I still think this is an issue, but it's just hard to replicate multiple times. If someone else gives it a go and can't replicate it then I think it's worth closing for the low replication rate. I'll leave the ball in @arcturus2 's court on this one.

**Comment by GammaVel** [comment] 2021-08-20 07:04
HI @Nova-2119 , I tried really hard to replicate this one and my DFs are getting populated even up to 300,000 when there are many not null values. I'll close this off for now but if you can replicate it with a particular graph please let us know how you did it.

**Closed by GammaVel** 2021-08-20 07:04 UTC
Labels: bug
