### ISSUE TITLE
Analytic View Pane Null Pointer

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#456] opened 2020-04-23 05:40 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

A null pointer with the below stack trace occurs when no graph is opened, and categories or questions are opened and selected/deselected. I then opened a new blank graph and noticed the exception.
I did not notice the exact point in time which this occurred - but it does happen. 
```
java.lang.NullPointerException
	at au.gov.asd.tac.constellation.views.analyticview.AnalyticConfigurationPane.lambda$updateSelectablePluginsParameters$29(AnalyticConfigurationPane.java:528)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at au.gov.asd.tac.constellation.views.analyticview.AnalyticConfigurationPane.updateSelectablePluginsParameters(AnalyticConfigurationPane.java:524)
	at au.gov.asd.tac.constellation.views.analyticview.AnalyticConfigurationPane.setPluginsFromSelectedQuestion(AnalyticConfigurationPane.java:509)
	at au.gov.asd.tac.constellation.views.analyticview.AnalyticConfigurationPane.lambda$new$17(AnalyticConfigurationPane.java:236)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
[catch] at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
### Steps to Reproduce

1. Open Analytic View
2. Open Categories and Questions
3. Select/Deselect various plugins and parameters (Exception may have occurred here)
4. Open a new blank graph. (Exception may have occurred here)

The exact replicator is not known. Running .exe of 2.0 beta
**Expected behaviour:** 
No exception

**Actual behaviour:** 
Exception - Null pointer

**Reproduces how often:** 
Only appeared once

### Additional Information
Does not appear to occur in previous releases

**Comment by formalhaut69** [comment] 2020-04-24 00:32
I was able to reproduce this after a number of attempts. 
![image](https://user-images.githubusercontent.com/58677762/80161778-983db100-8610-11ea-8d98-43fb35369ef9.png)

I clicked a few analytics in the centrality category and then created a new graph. I don't think this issue is new to v2, I think its just difficult to reproduce and occurs very rarely.

**Comment by antares1470** [comment] 2020-05-14 03:31
@formalhaut69 I know this was a little bit ago but do you happen to remember exactly which analytics in the centrality category you selected when the error occurred?

Also when trying to reproduce the error, did you close Constellation between each attempt or just close the graph between each attempt?

**Comment by formalhaut69** [comment] 2020-05-14 04:56
> 
> 
> @formalhaut69 I know this was a little bit ago but do you happen to remember exactly which analytics in the centrality category you selected when the error occurred?
> 
> Also when trying to reproduce the error, did you close Constellation between each attempt or just close the graph between each attempt?

Sorry @antares1470 I don't remember which options I selected. At first I was just selecting options at random which got it to occur. I had another go at this issue a few weeks ago and I went through and tested each section by selecting each option from it, then I selected a bunch at random again and still couldn't reproduce it ☹️. 

I was doing both, I tried a few times just closing the graph and then I would restart constellation. If I recall correctly, the one time I reproduced it, it occurred right after I had relaunched constellation.

**Comment by antares1470** [comment] 2020-05-14 05:03
> Sorry @antares1470 I don't remember which options I selected. At first I was just selecting options at random which got it to occur. I had another go at this issue a few weeks ago and I went through and tested each section by selecting each option from it, then I selected a bunch at random again and still couldn't reproduce it ☹️.
> 
> I was doing both, I tried a few times just closing the graph and then I would restart constellation. If I recall correctly, the one time I reproduced it, it occurred right after I had relaunched constellation.

Cheers @formalhaut69. I'm just looking for more reliable ways of replicating the bug. It sounds like you've exhausted most of the options though so I guess my primary focus will be on the stack trace that you and @aldebaran30701 managed to get

**Comment by antares1470** [comment] 2020-05-15 03:52
I think I've managed to find a way to get the exception to occur more often than not. 
```
else if (questionListPane.isExpanded() && currentQuestion != null) {
     pluginList.getItems().forEach(selectablePlugin -> {
          lock.lock();
          try {
               selectablePlugin.parameters.updateParameterValues(selectablePlugin.updatedParameters);
               currentQuestion.initialiseParameters(selectablePlugin.plugin, selectablePlugin.parameters);
          } finally {
               lock.unlock();
          }
     });
}
```
This is lines 527-537 of `AnalyticConfigurationPane.java` (where the exception occurs). If you run Constellation in debug mode and put a breakpoint somewhere in the if block before the finally block (the exception occurs in the last line of the try block), following the steps that have been outlined above (doesn't matter which category analytics you select) should see the exception be produced (note: this only works the first time after running Constellation, you need to re-run it to replicate it again).

Without that breakpoint, the exception (as observed previously) occurs far less frequently (this includes adding a breakpoint to the line in the finally block). What this seems to suggest to me is that there is a timing aspect involved to this exception

**Closed** 2020-05-18 06:39 UTC
Labels: bug, v2.0.0-beta
