### ISSUE TITLE
Sphere Graph / Renderer speed decreased

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#838] opened 2020-09-07 04:32 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Lately I've noticed building sphere graphs - or more specifically rendering them has decreased drastically in performance.  I feel like I used to be able to make a graph with 10000 vertices without issue. Now it takes what seems like minutes to render anything.

### Steps to Reproduce

1. new graph
2. build sphere graph
use 1000/10000 nodes to see the delays. Compare with other release versions.

**Expected behaviour:** loads fast

**Actual behaviour:** loads slow

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Nova-2119** [comment] 2020-09-17 05:38
Okay so I have done some comparisons of rendering speed.
I didn't do anything fancy, just measured the time from clicking open until the graph rendered using a stopwatch.

V2 is definitely slower on average, but the amount of time it takes to render things also seems to vary quite alot compared to v1 which has very consistent load times. Sometimes V2 would be as quick as V1, but other times it took over twice as long.

Attached is a horrific notepad of render times.

**Comment by Nova-2119** [comment] 2020-09-17 05:39
[Render time comparison.txt](https://github.com/constellation-app/constellation/files/5236564/Render.time.comparison.txt)

**Comment by Nova-2119** [comment] 2020-09-17 05:51
The over 7:30 one is interesting....I got bored of waiting and went to have lunch...but it had rendered when I go back so it wasn't like an error or something...it was just genuinely that slow.

**Comment by arcturus2** [comment] 2020-09-18 02:10
>Sometimes V2 would be as quick as V1, but other times it took over twice as long.

@Nova-2119 this was what I was experiencing too so it is good to know I'm not alone on this (and have gone insane). The txt is good though as it shows how bad it is. I will share some findings in a bit.

**Comment by Nova-2119** [comment] 2020-09-23 05:06
Okay so this is fairly difficult/involved to chase down, which is fun but means progress is slow.

I noticed a discrepancy in the amount of invocations for some of the methods that chew up a bunch of CPU time and figured this may be the cause for some of the difference. Going up the stack I think this all comes from V1 calling NodeLabelBatcher twice whilst V2 calls it three times. This seems to be due to the addition of an extra VERTEX_VISIBILITY and CONNECTION_VISIBILITY in the change set. 
I think these were the only duplication's in the change set... (but now I say that i'm unsure...they were definitely the only sequential duplication's, I will check).
Anyway,  it looks like this is a by-product of the creation of vertexLayerVisibility and transactionLayerVisibility recordChanges. Essentially opening a new graph is triggering these in addition the the normal vertexVisibility and transactionVisibility recordChanges which act the same.

Next step is to comment these out and confirm whether it: 
1) Brings the amount of times NodeLabelBatcher is invoked in line with V1
2) Reduces or eliminates other discrepancies in invocations further down the stack
3) Reduces the average render time
4) Reduced the variability in render time evident in V2 but not in V1 (from my limited experimentation).
I'll do this by commenting out the xLayerVisibility recordChange types and then profiling opening a graph to see how it affects things. I've already confirmed I can do this and still build and run the app.

If some of these are true and its a meaningful improvement, I'll then chase down how to fix this correctly as I assume just commenting them out is ruining the layers view.
My initial instinct is that maybe calculatePertinentChanges should be removing the duplicates or at least doing something to stop this behavior....that's a shot in the dark though and not a well thought out or particularly educated guess!

**Comment by Nova-2119** [comment] 2020-09-24 05:24
Updated the Render Time Comparison. It now shows that the change described above bring V2 render times in line with V1....except for a sphere graph of size 50000 with few transactions, where it is slower takes significantly longer after opening it for the first time (which is usually about 10 seconds slower). Its pretty bizarre.
Ill move onto figuring that out once I have a proper equivalent solution to the changes above.

**Comment by Nova-2119** [comment] 2020-09-28 07:27
Since my last comment ive spent alot of time experimenting with the visualManager/visualProcessor and related classes in order to build an understanding of how visual updates work and what the correct solution might be.
Ive also spent some time playing with the graph listeners to understand how they work.

I think the core issue is that when you open a graph the indigenous change listener gets created and then panics because everything has changed (as nothing existed before) and hence adds all of the visualChanges to the list of changes to be performed. This work but I strongly suspect its overkill, so my focus has been on avoiding this without resorting to checking for duplicate/overlapping visualChanges at a later stage and removing them, i'd rather stop the duplicates form happening to begin with.

Current effort is focused on initialising the modification counters in the GraphVisualAccess so that no indigenous changes are recorded initially and then calling refreshVisualProcessor to produce the initial render of the graph instead.

**Comment by Nova-2119** [comment] 2020-09-29 06:17
I have managed to achieve the above and this has made rendering the graph much quicker.
Render times are now even quicker than those in V1, however there is still an issue with subsequent graph opens being slower than the first. These slower opens are still faster than V1, see the Render Time Comparison Attatched.

[Render time comparison.txt](https://github.com/constellation-app/constellation/files/5296796/Render.time.comparison.txt)

**Comment by Nova-2119** [comment] 2020-09-29 06:22
@arcturus2 I'm thinking its probably worse getting up a PR for the changes so far and getting it into testing. I have done some testing, and everything seems fine, but I can't rule out me missing an unintended side effect.

I would like to keep going on this ticket and see if I can figure out why opening the graph is slower after the first time. Given people often have more than one graph open it seems important to fix.

I might also have a look at the "Update graph views after the visualisation updates" idea mentioned in brainstorming ideas?

**Comment by Nova-2119** [comment] 2020-10-02 03:04
So it turns out the reason it is slower to open a graph multiple times is actually not due to opening a second graph but due **having just closed a graph_**. 
Closing a graph calls the GraphRenderable.dispose()  method which calls GLVisualProcessor.rebuild() which triggers a fullRefresh of the graph. This means that when you close the graph it actually rebuilds it in the background and never displays it to the screen. The slow down observed is actually it waiting for the refresh from the close to finish prior to performing a new refresh!
This is why the times were roughly twice as slow and more variable, it doing the same thing twice and the amount of time between me closing the last graph and opening the new one explains the variability :)

Some digging showed me that reshape is called whenever a refresh should be performed, so I have moved the call to rebuild out of dispose and into that method. This has removed the slowdown affect and as far as I can tell everything behaves as it should.

I am doing some further investigating so that I can be sure that is the correct method to call rebuild in, display() and init() are alternatives that might work. I need to become familiar with exactly when each is and isn't called and how that correlates to when a refresh is and isn't required.

[Render time comparison.txt](https://github.com/constellation-app/constellation/files/5315768/Render.time.comparison.txt)

**Comment by arcturus2** [comment] 2020-10-02 03:33
That is truely remarkable performance improvements @Nova-2119 

I've been playing in your branch and one of the slow bits is the `g2d.clearRect(0, 0, drawing.getWidth(), drawing.getHeight());` call and I was wondering if there was a way to create a g2d object that is already clearRect'd that can be used instead of doing this every time.

![image](https://user-images.githubusercontent.com/39325530/94885416-772c9680-04b3-11eb-82fc-1a168f0ca7df.png)

Given Java is pass by reference this isn't straight forward. Being able to get a shallow/deep copy of the object might be enough. I will keep digging.

Commenting out this like makes it way way fast but you can't make out any of the labels lol.

**Comment by Nova-2119** [comment] 2020-10-02 05:47
> 
> 
> That is truely remarkable performance improvements @Nova-2119
> 
> I've been playing in your branch and one of the slow bits is the `g2d.clearRect(0, 0, drawing.getWidth(), drawing.getHeight());` call and I was wondering if there was a way to create a g2d object that is already clearRect'd that can be used instead of doing this every time.
> 
> ![image](https://user-images.githubusercontent.com/39325530/94885416-772c9680-04b3-11eb-82fc-1a168f0ca7df.png)
> 
> Given Java is pass by reference this isn't straight forward. Being able to get a shallow/deep copy of the object might be enough. I will keep digging.
> 
> Commenting out this like makes it way way fast but you can't make out any of the labels lol.

Oooh good catch, now that I think the higher level methods are broadly being called in the right places/the right amount of times im going to shift my focus to how to improve the efficiency of the lower level stuff and this is a good place to start!

**Comment by Nova-2119** [comment] 2020-10-02 05:50
Ive moved

> 
> 
> So it turns out the reason it is slower to open a graph multiple times is actually not due to opening a second graph but due having just **closed** a graph.
> Closing a graph calls the GraphRenderable.dispose() method which calls GLVisualProcessor.rebuild() which triggers a fullRefresh of the graph. This means that when you close the graph it actually rebuilds it in the background and never displays it to the screen. The slow down observed is actually it waiting for the refresh from the close to finish prior to performing a new refresh!
> This is why the times were roughly twice as slow and more variable, it's doing the same thing twice and the amount of time between me closing the last graph and opening the new one explains the variability :)
> 
> Some light digging showed me that reshape is called whenever a refresh should be performed, so I have moved the call to rebuild out of dispose and into that method. This has removed the slowdown affect and as far as I can tell everything behaves as it should.
> 
> I am doing some further investigating so that I can be sure that reshape is the correct method to call rebuild in, display() and init() are alternatives that might work. I need to become familiar with exactly when each is and isn't called and how that correlates to when a refresh is and isn't required. From names alone display feels like it should make more sense, but there's more digging to be done to understand exactly what that does.
> 
> [Render time comparison.txt](https://github.com/constellation-app/constellation/files/5315768/Render.time.comparison.txt)

After this investigation I have moved the call for rebuild into init(). I have done this because the refresh is only required after a dispose is called. In order to continue with a graph after a dispose is called an init must be called, hence it makes the most sense to put the rebuild call in init().

**Comment by arcturus2** [comment] 2020-10-06 00:20
@Nova-2119 your PR just keeps getting better. With your last change, I noticed a perf improvement which was when the graph resizes due to a view being docked or minimised, ALL graphs used to have the `GlyphManagerBI.renderTextAsLigatures()` called. Now it will only do this on the active graph and when you switch to the respective graph it will call `renderTextAsLigatures()`.

Now, from my last comment, I really do want to see if we can improve the performance of `renderTextAsLigatures()` which is basically the call to `clearRect()` as I originally thought the graphics card was slow to renderer a large graph but it turns out the slowest bit is the method `renderTextAsLigatures()` and soon after it completes the graph renders.

I spent a significant amount of time on Friday trying to reduce the calls to `clearRect()` but failed to - mainly due to how Java works with pass by reference for Objects. I tried doing something like this but I was just getting the reference to the same `Graphics2D` object so only the last node I created (using draw mode) would render 🙂:

```java
        Graphics2D g2d;
        if (G2D == null) {
            g2d = drawing.createGraphics();
            g2d.setBackground(new Color(0, 0, 0, 0));
            g2d.clearRect(0, 0, drawing.getWidth(), drawing.getHeight());
            g2d.setColor(Color.WHITE);
            G2D = g2d;
        }

        g2d = G2D;

        g2d.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
        ...
```

I also trying converting `g2d` into a `byte[]` and restoring it byet there was issues with some of the dependent classes not implementing `Serializable`. After fixing that, I ended up with the same issue as above, only the last node's label was rendered.

I think I am half way there and it is possible; but not sure how to proceed with it.

**Comment by Nova-2119** [comment] 2020-10-20 04:59
In the branch https://github.com/constellation-app/constellation/tree/performance/838-MultiThreading I have continued this ticket  with a focus on multi-threading where possible to improve speed outcomes.
Since then I have managed to multi-thread both the NodeLabelBatcher and the ConnectionLabelBatcher which has led to large improvements in rendering speed.
The branch is still a work in progress, more work needs to be done to optimise the amount of threads being created and potentially improve upon the current implementation. 
Attached is an updated copy of the render time comparison with the latest rendering times in both the case where just NodeLabelBatcher is multi-threaded and both NodeLabelBatcher and ConnectionLabelBather are multi-threaded.
[Render time comparison.txt](https://github.com/constellation-app/constellation/files/5406369/Render.time.comparison.txt)

**Comment by Nova-2119** [comment] 2020-10-22 04:22
There may be a memory issue with https://github.com/constellation-app/constellation/tree/performance/838-MultiThreading it seems like it may be using double the memory of the current master. Need to do more digging.

This is why I should never say that im close to the end or wrapping up, I always find something almost immediately after!

**Comment by arcturus2** [comment] 2020-10-22 09:08
@Nova-2119 thanks for the update. No worries at all. What you have done thats now in master is a massive improvement.

**Closed** 2020-11-10 02:09 UTC
Labels: bug, performance
