### ISSUE TITLE
Improving UX on Error Message Handling

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#48] opened 2019-07-26 04:58 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

As a user
i want better indications about errors
so that my experience is enhanced and i get more contextual information.

There is potential for UX improvements around error handling. Some examples of improvements that could be added include:
* changing the colour of the plugin field that caused the error to occur (e.g. red)
* easy-to-understand messages making it clear to the user why an error has occurred.
* replace stack trace prints and other exception-generated messages with custom messages in accordance with the previous point

Discussion has allowed a better understanding to occur - notably that this ticket will hold information about the handling of expected errors and not runtime null pointer errors.

* [ ] Validate input fields
* [ ] Validate preconditions before execution
* [ ] Handle expected errors gracefully
* [ ] Design an extensible way so all plugins have consistent behaviour upon errors.

**Comment by aldebaran30701** [comment] 2021-05-25 06:37
This issue may need some more clarification - Does it refer the error messages that occur when something fatal has happened (null pointer etc.) If it does, some digging may need to occur to decide if there is a way to capture that exception and log it as an exception window to the user. 

If it refers to an error in an input field, like trying to create more than 32 layers - then maybe a systematic review of input cases should be had. ie. launching a dialog box which describes the error to the user. This would take much longer to implement as it's a case-by-case solution.

**Comment by arcturus2** [comment] 2021-06-02 06:03
It is a review for all the above you mentioned @aldebaran30701. We have the ability to show popups and there is also the ability for parameters to indicate something is wrong. This isn't widely used so some consistency with the Data Access View and other views is required. I am OK if all we do is document what we expect to do in each case and take it from there.

![Screenshot from 2021-06-02 16-00-48](https://user-images.githubusercontent.com/39325530/120431465-df71a600-c3bb-11eb-8102-0608fbbf204f.png)

**Comment by antares1470** [comment] 2021-10-07 04:02
Now that the changes I've made have been merged in, this is what I think could still be done as a part of ticket:
- ensure that any required parameter fields for a plugin are filled with sensible default values
- either highlight required fields in plugin execution submitted without value or highlight as soon as there is no value in a required field

After that work is done, this ticket should be able to be closed

**Comment by antares1470** [comment] 2021-10-19 00:42
I had looked at these when I was working on my PR. These are definitely controlsfx issues and while it would good for us to be able to fix them, they are definitely issues that should be fixed in controlsfx. Having done some quick testing, I'm not even sure whether we can even handle these at the Constellation level

**Comment by GammaVel** [comment] 2022-05-02 04:20
On the Analytic view the Transactions is indicated as mandatory when it is not a mandatory field in all cases. See below for an example. The calculation still runs however the field is indicated as mandatory:

![image](https://user-images.githubusercontent.com/83679004/166183837-f7ea60e1-7214-42d0-9c0a-a1be809f5835.png)

**Comment by GammaVel** [comment] 2022-05-02 05:09
I have also made a new issue for the runtime error that gets displayed when text is entered into a numeric field - see #1687

**Comment by antares1470** [comment] 2022-05-02 05:26
> I have also made a new issue for the runtime error that gets displayed when text is entered into a numeric field - see #1687. This is probably similar to one of the ones that @aldebaran30701 has highlighted above. I have tested this errors and they are all still occurring.

Correct @GammaVel the issue you've identified is the same as the one above from @aldebaran30701. See the comment below that one that I made regarding it. Basically the issue is one with the component being used rather than Constellation but can't really be fixed (from my previous attempts) at the Constellation level.

**Comment by GammaVel** [comment] 2022-05-05 03:31
Thanks @antares1470 for your feedback and interesting to know it can't be fixed at the constellation level. Thanks for updating Transactions to be non-mandatory in the Analytic View.

**Closed by GammaVel** 2022-05-05 03:31 UTC
Labels: enhancement, ux
