### ISSUE TITLE
Cannot export tables to excel

### ISSUE THREAD

**Issue by Nova-2119** [constellation-app/constellation#692] opened 2020-07-15 01:47 UTC
### Description
In table view I try to export data to excel. It looks like it all works, I save on my desktop but then nothing actually happens (the document doesn't appear). I asked a teammate to do the same thing, he went through the same process as I did, and it worked, so i'm not sure what the issue is.

This seems to be an intermittent issue and the exception is:
Java.io.IOException: The System cannot find the path specified

### Steps to Reproduce
Non-provided

**Expected behaviour:** [What you expect to happen]
Excel file should be saved in the specified file location

**Actual behaviour:** [What actually happens]
File is not save and an error occurs.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Unknown but not 100%

**Comment by arcturus2** [comment] 2020-07-15 18:15
This is a duplicate of #329 which has been resolved.

**Closed by arcturus2** 2020-07-15 18:15 UTC
Labels: bug, duplicate
