### ISSUE TITLE
Analytic View Pane Layout Scaling

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#455] opened 2020-04-23 05:31 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The Analytic View information panel does not scale well and hides the majority of the text making it unreadable.

### Steps to Reproduce

1. Open Analytic view
2. Open any panel with information
ie. 
 - "Has Closest Relationship" and view the Aggregation Method text when scaling
 - "Betweenness Centrality Analytic" and view the parameters like 'include...'

**Expected behaviour:** [What you expect to happen]
Scaling to show the rest of the word
**Actual behaviour:** [What actually happens]
Word is hidden and the drop down box just gets scaled out
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Additional Information
![resizeAnalyticView](https://user-images.githubusercontent.com/58677759/80062566-3844fd00-8573-11ea-9ed8-e0bc64c43b2e.gif)
![resizeAnalyticView2](https://user-images.githubusercontent.com/58677759/80062572-3aa75700-8573-11ea-9a84-cb0d4d6c0b7b.gif)

**Comment by aldebaran30701** [comment] 2020-04-23 06:01
To add to this, When running a plugin, half of the preferences are hidden and cannot be located easily.
No scroll wheel or drag bar or hide option for the report section which makes it very difficult to see which parameters have been selected. 
![image](https://user-images.githubusercontent.com/58677759/80064470-4c8af900-8577-11ea-885b-2994c189bde4.png)

**Comment by cygnus-x-1** [comment] 2020-04-23 07:54
Haha i've been complaining about these issues for years. Early on we did attempt to fix them but couldn't figure out the JavaFX intricacies... I'd love for someone else to give it a go.

**Comment by cygnus-x-1** [comment] 2020-04-23 07:55
This is also a duplicate of https://github.com/constellation-app/constellation/issues/363 - i'll keep this one open and close the other.

**Comment by antares1470** [comment] 2020-05-25 00:11
Does this need to be closed?

**Comment by aldebaran30701** [comment] 2020-05-25 00:18
@antares1470 I believe it satisfies the ticket so I'm fine with it being closed.

**Closed** 2020-05-25 00:44 UTC
Labels: bug, user relevant, ux
