### ISSUE TITLE
Layers view - Union of layers is not being shown on the graph

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1182] opened 2021-08-10 23:34 UTC
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
In the layers view it is possible to set up multiple query layers for inspection. The query layers are working individually and if there is one of each different type - eg. one vertex query and one transaction query. However if there are two or three transaction or vertex queries the graph is not showing the union of all the layers. It shows the last query layer. The detailed steps and screenshots help explain the issue

### Steps to Reproduce

1.  Open Constellation graph and Layers view
2.  Set up a query layer for transaction - e.g. - Type =='Communication'
3.  View the results -> as expected
4.  Add in another query layer for transaction - e.g. Type == 'Correlation' (or whatever type exists on your graph)
5.  View the results -> only the last transaction layer is shown
6.  Repeat with a couple of vertex attributes -> same result
7.   Turn on all the layers of the graph > I would expect this to return the same results as the default (show all) view -> only the last two layers are shown
 
-->

**Expected behaviour:** the layers build on top of each other, if I have two transaction layers selected they are both shown on the graph, not just the last selected one. 

**Actual behaviour:** as per the Repro Steps, the layers are not building on top of each other. 

**Reproduces how often:** 100%

### Additional Information

![image](https://user-images.githubusercontent.com/83679004/128947970-acef9fc6-0f71-4abb-a95d-fbbd806d729e.png)

**Comment by aldebaran30701** [comment] 2021-08-11 02:08
When using queries, the selected layers will be intersected as the resultant graph. 
When using static layers, the selected layers will be unified as the resultant graph.

I hope this is easy to comprehend, because for an element to match both queries which are enabled, they must satisfy the constraints listed in the query. 
eg. it will be impossible for a transaction element to have both the `communication` and `correlation` type.

The reason it works on the last two queries for selecting all layers, is that the elements can match both queries on different element types. 
eg. it is possible for a vertex or transaction element to be of type `network` or of type `email`

I've documented some of this in the help pages, I can't recall to what level of detail it is listed though. 

A new feature in #809 is about handling union and intersection of each layer. Noted that to implement this it will be a large undertaking and may not be implemented for some time.

To give some insight into why this is the way it is, the layers view will iterate over all layers, and for each query, will check over each element that it fits the constraint in the query entry box. If it does fit, it is toggled to be visible.
Once it gets to the last query for each type (last transaction query, and last vertex query) those are the last checked against the graph. Those are the visible elements that persist on the graph as being matched. 

For Manual layers, they are treated as being within a layer no matter what its attributes are valued at. This means they will always match against the rule of being within an active layer. No other manual layer will negate the fact that this element is visible. Effectively making it a union of the enabled layers.

**Comment by antares1470** [comment] 2021-08-11 02:39
> When using queries, the selected layers will be intersected as the resultant graph.

If that is the intended behaviour, I think there is still a bug here. I've also seen what @GammaVel has seen (just forgot to put up an issue...). If the queries are meant to be an intersection, I would expect nothing to appear on my graph in the given scenario rather than the graph elements satisfying the last query.

That being said, my gut always thought selecting 2 layers would be a union rather than intersection. Having different logics depending on how the layer is created will also cause confusion. Maybe some of that will be resolved in #809 but I think there is still something to be addressed here

**Comment by aldebaran30701** [comment] 2021-08-11 06:27
Agreed on the last point about it being what you would expect. The issue is that since the query refactoring done a while back, both layer types have been slightly different in implementation. Partly because of the complexity needed to get the expressions working in the current framework. I've had the union and intersection on the back of my mind, and have not found a proper resolution implementing them both (or making layers view query types more consistent, for that matter). 

I think the initial design of an expression worked perfectly for making one layer, but the code within layers view to handle multiple layers might need something to overlay each selection onto a 'resultant' graph. This will need some thinking

**Comment by GammaVel** [comment] 2021-08-13 00:18
Thanks @aldebaran30701 for pointing out #809. Glad this is being considered as it would be useful to know what type of calculation was being performed when multiple layers are selected and the rules that are sitting behind them.  I'm leaning towards @antares1470 opinion that when you turn on multiple layers that keep adding to the graph, even when there is an "Or" statement in the query.

**Comment by Delphinus8821** [comment] 2022-10-18 03:51
Closing as this bug was fixed with #1690. The information from this ticket regarding the intersection of layers will be included in #809.

**Closed by Delphinus8821** 2022-10-18 03:51 UTC
Labels: bug
