### ISSUE TITLE
Search conversations

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#887] opened 2020-11-05 21:46 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Would it be possible to add a search function to the conversation view? Similar to excel in that it would jump to a bubble matching keywords/characters chosen.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by mimosa2** [comment] 2020-12-01 07:00
A a branch called "conversation_search_option" is created with the work @mimosa2 has already done on this ticket. There is one more task on this which @mimosa2 couldn't complete.  If anyone can continue on this to complete that task would be great.
The issue is when search found a string in a bubble which is hidden in the conversation view (i.e need to scroll down to view the bubble). It would be nice if the bubble set focus (scroll up) itself without user to scroll down to view the searched string.

**Comment by sol695510** [comment] 2021-01-28 03:27
![convo1](https://user-images.githubusercontent.com/58677774/106085439-1c106500-6170-11eb-892d-e118271e46fe.gif)
^Current context menu functionality. Previously available "Select All" has been omitted since the current type of JavaFX region (TextFlow) being used is not selectable/highlightable, so now "Copy" simply copies all text on a selected conversation bubble to the system clipboard.

![convo2](https://user-images.githubusercontent.com/58677774/106085603-6eea1c80-6170-11eb-8627-cd8d81d212a4.gif)
^Current conversation search functionality. All instances of searched text are shown via styling the text with the JavaFX region TextFlow.

**Comment by sol695510** [comment] 2021-02-25 23:42
@antares1470 @mimosa2 Can this ticket be closed in favour of moving ticket #958 onto the board to replace it? Although they ask for the same feature, this ticket refers to the branch for this PR #957, which should be closed soon.

**Comment by mimosa2** [comment] 2021-02-26 00:12
#957 Can be closed and #958 can be moved into the board.

**Comment by antares1470** [comment] 2021-02-28 21:45
> @antares1470 @mimosa2 Can this ticket be closed in favour of moving ticket #958 onto the board to replace it? Although they ask for the same feature, this ticket refers to the branch for this PR #957, which should be closed soon.

@sol695510 Assuming everything in #957 is all good, this ticket can serve as the first implementation of this feature (which the PR would achieve) and so we can close it once we're satisfied after testing that there aren't any problems introduced. #958 would then serve as an improvement on this and can be done separately from the current PR.

**Closed** 2021-08-17 03:48 UTC
Labels: enhancement
