### ISSUE TITLE
Nullpointer error when closing a graph.

### ISSUE THREAD

**Issue by mimosa2** [constellation-app/constellation#598] opened 2020-06-23 03:09 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

A nullpointer exception occurs when closing a empty or non-empty graph. 

### Steps to Reproduce

1. Open a new graph or recent graph. 
2. Close graph by File -> close OR close the tab
3. Open a new graph or recent graph.
4. Update the graph
5. Close graph by File -> close OR close the tab
6. After Save the graph, Close graph by File -> close OR close the tab

**Expected behaviour:** Should close without any errors.

**Actual behaviour:** Nullpointer error thrown.

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
![Close graph error](https://user-images.githubusercontent.com/54261086/85356614-b7928500-b552-11ea-87c3-7386a1a077db.PNG)

**Comment by arcturus2** [comment] 2020-06-23 03:32
Thanks @mimosa2 for reporting this. I saw this some time ago but wasn't able to put a reproducer together.

This is something new in v2 and my thought is that on close. a plugin is trying to run to perhaps update state or something like that and by the time it runs the graph is gone (i.e `null`) so it fails.

The logs might show which plugin was running when it closed.

**Comment by aldebaran30701** [comment] 2020-07-03 00:06
@arcturus2 If we found which Update State Plugin was run and caused this issue, would we be adding a null check before it executes any code? I feel like it wouldn't reach that section of code. 
Maybe that null check which was merged in #616 would solve this issue? I have not been able to reproduce the issue even before the fix was merged in.

**Comment by arcturus2** [comment] 2020-07-03 03:52
> @arcturus2 If we found which Update State Plugin was run and caused this issue, would we be adding a null check before it executes any code? I feel like it wouldn't reach that section of code.
> Maybe that null check which was merged in #616 would solve this issue? I have not been able to reproduce the issue even before the fix was merged in.

Hi @aldebaran30701 it turns out to be the Quality Control View update state causing the null pointer. Essentially the graph is closed and it tries to update the state calling `getActiveGraph` which is null. I've fixes this in my #621 PR.

**Comment by arcturus2** [comment] 2020-07-03 03:56
Hey @aldebaran30701 just catching up and noticed you did #619 which will also help with fixing this one. I've applied the same fix in #621.

**Closed** 2020-07-07 03:02 UTC
Labels: bug
