### ISSUE TITLE
macOS - Layers View - Deletion of Layer not working as expected

### ISSUE THREAD

**Issue by royalflush007** [constellation-app/constellation#1433] opened 2021-09-21 02:01 UTC
### Prerequisites

- Constellation is installed on macOS

### Description

This issue was noticed when running the v2.4.0-rc-2 on the macOS.

When a user tries to add a new Layer via the Layer-view, the layer cannot be deleted. Any additional layers created
are appended to the row in which the existing layer is displayed on the panel, creating N amount of sub-layers

### Steps to Reproduce

1.  User clicks - > Experimental - > Layers View
2. In the Layers View Panel, click - "Add new layer"
3. Click the "Delete" button next to your new layer - The layer will not be deleted
4. Click "Add new layer" button again, a new layer will be added but next to the layer you wanted to delete in previous step. (take note of the layer number assigned)
5. Click the "Delete" button next to the sub-layer - Delete will not work
6. Click "Add new Layer" - a new sub-sub layer is then created.

**Expected behaviour:** 

Any layers added by the user should be removable.

### Additional Information

![1](https://user-images.githubusercontent.com/89366901/134100592-cc5457c5-7371-4ed8-8085-318b304d77fc.png)

![2](https://user-images.githubusercontent.com/89366901/134100622-6d858244-727f-4a6e-8bf7-b8507535e9fc.png)
![3](https://user-images.githubusercontent.com/89366901/134100644-b9528c74-9074-4ad1-8cc0-d871391b343f.png)

**Comment by aldebaran30701** [comment] 2021-09-21 03:21
Hi there @royalflush007 Do you happen to have a graph open while reproducing this issue?
I feel this is a duplicate of #1334

There will be a fix in the future to only enable the panel when there is a graph. This would make both issues redundant I feel.

**Comment by antares1470** [comment] 2021-12-06 21:34
I think as mentioned this is a duplicate of #1334 which has now been closed so I'll close this ticket as well

**Closed by antares1470** 2021-12-06 21:34 UTC
Labels: bug
